### ISSUE TITLE
Improve NPM documentation

### ISSUE THREAD

**Issue by cabelitos** [profusion/use-location-query-state#9]
## 🚀 Feature Request

Hello everyone, just wanted to point out that currently the NPM package does not any docs or links to this repo.
It would be nice to have it, so others may know what this library is is about and its repository.

Reference:
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/984610/203283116-f96c9cb1-e80b-4795-b6e8-bc6fcf73f310.png">

**Comment by felipebergamin** [comment]
Hello, @cabelitos :D 

We've just published v1.0.4 to npm with a README and other minor fixes.

Thank you for your contribution ;)
